### ISSUE TITLE
CrashLoopBackOff docker image

### ISSUE THREAD

**Issue by muhammedMoussa** [wiremock/helm-charts#27]
### Proposal

getting `CrashLoopBackOff` while installation

### Reproduction steps

- clone repo
- `helm upgrade --install <release_name> ./chart/<chart_name>`
- `kubectl get pods`

<img width="605" alt="image" src="https://github.com/wiremock/helm-charts/assets/18468244/413deb78-2331-4cc9-9068-a1285a8f651f">

**Comment by sigurdblueface** [comment]
you could try using `holomekc/wiremock-gui:2.35.0.1` image
